{% set name = "jupytab-server" %}
{% set version = "0.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbf18b3ac1817f274fd1693e80d02c995bcaa4d0e92811c1c038e4abd607d385

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  noarch: python
  entry_points:
    - jupytab=jupytab_server.jupytab:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jupyter_kernel_gateway

test:
  commands:
    - jupytab --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CFMTech/jupytab
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Connect Tableau to your Jupyter Notebook

  description: |
    Jupytab Server allows you to explore in Tableau data which is generated
    dynamically by a Jupyter Notebook. You can thus create Tableau data
    sources in a very flexible way using all the power of Python.
    This is achieved by having Tableau access data through a web
    server created by Jupytab.
  doc_url: https://github.com/CFMTech/jupytab
  dev_url: https://github.com/CFMTech/jupytab

extra:
  recipe-maintainers:
    - js-dieu
